refactor: move notification icons to themes
Signed-off-by: Boris Yumankulov <boria138@altlinux.org>

diff --git a/build-aux/share/portproton/scripts/functions_helper b/build-aux/share/portproton/scripts/functions_helper
--- a/build-aux/share/portproton/scripts/functions_helper
+++ b/build-aux/share/portproton/scripts/functions_helper
@@ -135,8 +135,10 @@ rm_from_array () {
 }
 
 fatal () {
-    #TODO
-    pw_notify_send -i error "$@"
+    if [[ -z "$*" ]] ; then
+        set -- "Fatal error"
+    fi
+    python_module dbus_tools notify -i error "$@" &>/dev/null
     print_error "$@"
     stop_portproton
     exit 1
@@ -562,48 +564,6 @@ var_ld_library_path_update () {
     else export LD_LIBRARY_PATH="${1}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
     fi
 }
-
-# GUI NOTIFY SEND
-pw_notify_send () {
-    local icon title body app timeout OPTIND
-    app="ru.linux_gaming.PortProtonQt"
-    timeout="5000"
-    OPTIND="1"
-    while getopts a:i:t: opt ; do
-        case "$opt" in
-            a)
-                app=$OPTARG
-                ;;
-            i)
-                case "$OPTARG" in
-                    info) local OPTARG="${PORT_IMG_PATH}/notify/info.svg";;
-                    warning) local OPTARG="${PORT_IMG_PATH}/notify/warning.svg";;
-                    error) local OPTARG="${PORT_IMG_PATH}/notify/error.svg";;
-                esac
-                icon=$OPTARG
-                ;;
-            t)
-                timeout=$OPTARG
-                ;;
-            *)
-                echo "usage: $0
-                [-a] name application (PortProtonQt default)
-                [-i] info, warning, error (none default)
-                [-t] timeout in ms (5000 default)" >&2
-                return 1
-                ;;
-        esac
-    done
-    shift $(( OPTIND - 1 ))
-    [[ "$1" == "--" ]] && shift
-    title="$1" ; shift
-    body="$*"
-
-    python_module dbus_tools notify \
-        -a "$app" -i "$icon" -t "$timeout" -- "$title" "$body" &>/dev/null
-    return 0
-}
-export -f pw_notify_send
 
 check_gamescope_session () {
     if [[ -n "$GAMESCOPE_IN_USE" ]]
@@ -2331,7 +2291,7 @@ pw_create_gui_png () {
 pw_create_unique_exe () {
     BASEDIR_GAME="$(dirname "$PW_EXE_FILE")"
     if [[ -d "$BASEDIR_GAME" ]] ; then
-        pushd "$BASEDIR_GAME" || fatal
+        pushd "$BASEDIR_GAME" || fatal "Failed to enter game directory: $BASEDIR_GAME"
         BASENAME_GAME_EXE="$(basename "$PW_EXE_FILE")"
         if [[ -n "$1" ]] ; then
             BASENAME_GAME="$(basename "$1" .exe).exe"
@@ -2344,7 +2304,7 @@ pw_create_unique_exe () {
             print_warning "There are no arguments for creating a symbolic link! Skip it..."
         fi
         try_remove_file "${PW_EXE_FILE}.ppdb"
-        popd || fatal
+        popd || fatal "Failed to return from game directory: $BASEDIR_GAME"
     fi
 }
 
